Controllers/PackageController.cs
using Graduation_Core.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;

namespace Graduation_Core.Controllers
{
    public class PackageController : Controller
    {
        private readonly DMSContext db = new DMSContext();
        private readonly IConfiguration _config;
        private IHostingEnvironment _hostingEnvironment;
        public PackageController(IConfiguration config, IHostingEnvironment hostingEnvironment)
        {
            _config = config;
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Send()
        {
            var cities = db.City.ToList().Select(c => new CityModel() { ID = c.CId, Name = c.CName }).ToList();
            cities.Insert(0, new CityModel() { ID = 0, Name = "==== Select City ====" });
            if (HttpContext.Session.GetString("username") != null)
            {
                ViewBag.mcities = cities;
                var SID = long.Parse(HttpContext.Session.GetString("uid"));
                var SCity = db.SenderInfo.SingleOrDefault(s => s.SId == SID).SCId;
                ViewBag.scid = SCity;

            }
            Random rand = new Random();
            long PackageID = Math.Abs((db.PackagesInfo.ToList().Last().PId + rand.Next(100, int.MaxValue)) % int.MaxValue);
            HttpContext.Session.SetString("pid", PackageID.ToString());
            ViewBag.pid = HttpContext.Session.GetString("pid");
            dynamic model = new ExpandoObject();
            model.p = new PackagViewModel();
            model.s = new SenderViewModel();
            model.r = new ReciverViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Send(SenderViewModel s, PackagViewModel p, ReciverViewModel r)
        {
            if (s.Name != null && p.Fargial != null && r.Name != null)
            {

                Random rand = new Random();
                City SenderCity = db.City.FirstOrDefault(c => c.CId == s.C_ID);
                City RecieverCity = db.City.FirstOrDefault(c => c.CId == r.C_ID);
                if (HttpContext.Session.GetString("uid")!=null)
                {
                    long ReciverID = Math.Abs((db.ReceiverInfo.ToList().Last().RId + rand.Next(100, int.MaxValue)) % int.MaxValue);
                    long PackageID = long.Parse(HttpContext.Session.GetString("pid").ToString());
                    var price = Price(p.Wight, p.Fargial, p.Early) + RoadPrice(SenderCity.CName, RecieverCity.CName);
                    ViewBag.P_ID = PackageID;
                    //=========Sender Data===================//
                    var SenderID = long.Parse(HttpContext.Session.GetString("uid"));
                    //long SenderID = db.SenderInfo.
                    //============ Reciever Data ============//
                    ReceiverInfo Receiver = new ReceiverInfo()
                    {
                        RId = ReciverID,
                        RName = r.Name,
                        RAddress = RecieverCity.CName,
                        SId = SenderID,
                        RSsn = r.SSN,
                        RCDId = r.LocationID,
                        RCId = r.C_ID,
                        RAddressDetail = r.AddressDetails,
                        REmail = r.Email,
                        RMobile = r.Mobile,


                    };
                    //=========Package Data================//
                    PackagesInfo package = new PackagesInfo()
                    {
                        PId = PackageID,
                        Deleverydate = p.Date,
                        Earlydelivery = p.Early,
                        Description = p.Describtion,
                        PWeight = p.Wight,
                        PDeliverStatus = "no",
                        PFaragial = p.Fargial,
                        PPrice = price,
                        RSsn = r.SSN,
                        SSsn = s.SSN,
                        PLId = s.LocationID
                    };
                    db.ReceiverInfo.Add(Receiver);
                    db.SaveChanges();
                    db.PackagesInfo.Add(package);
                    db.SaveChanges();
                    SendMobileMessage(package, Receiver.RMobile);
                }
                else
                {
                    long SenderID = (long)Math.Abs((db.SenderInfo.ToList().Last().SId + rand.Next(100, int.MaxValue)) % int.MaxValue);
                    long ReciverID = Math.Abs((db.ReceiverInfo.ToList().Last().RId + rand.Next(100, int.MaxValue)) % int.MaxValue);
                    long PackageID = long.Parse(HttpContext.Session.GetString("pid").ToString());
                    var price = Price(p.Wight, p.Fargial, p.Early) + RoadPrice(SenderCity.CName, RecieverCity.CName);
                    ViewBag.P_ID = PackageID;
                    //=========Sender Data===================//
                    SenderInfo Sender = new SenderInfo()
                    {
                        SId = SenderID,
                        SAddress = SenderCity.CName,
                        SCDId = s.LocationID,
                        SCId = s.C_ID,
                        SEmail = s.Email,
                        SMobile = s.Mobile,
                        SAddressDetail = s.AddressDetails,
                        SName = s.Name,
                        SSsn = s.SSN,

                    };
                    //============ Reciever Data ============//
                    ReceiverInfo Receiver = new ReceiverInfo()
                    {
                        RId = ReciverID,
                        RName = r.Name,
                        RAddress = RecieverCity.CName,
                        SId = SenderID,
                        RSsn = r.SSN,
                        RCDId = r.LocationID,
                        RCId = r.C_ID,
                        RAddressDetail = r.AddressDetails,
                        REmail = r.Email,
                        RMobile = r.Mobile,


                    };
                    //=========Package Data================//
                    PackagesInfo package = new PackagesInfo()
                    {
                        PId = PackageID,
                        Deleverydate = p.Date,
                        Earlydelivery = p.Early,
                        Description = p.Describtion,
                        PWeight = p.Wight,
                        PDeliverStatus = "no",
                        PFaragial = p.Fargial,
                        PPrice = price,
                        RSsn = r.SSN,
                        SSsn = s.SSN,
                        PLId = s.LocationID
                    };
                    db.SenderInfo.Add(Sender);
                    db.ReceiverInfo.Add(Receiver);
                    db.SaveChanges();
                    db.PackagesInfo.Add(package);
                    db.SaveChanges();
                    SendMobileMessage(package, Receiver.RMobile);
                }
                
                return RedirectToAction("Index", "Home");
            }
            //Checked in
            ViewBag.Error = "Please Enter Data Correctly ";
            return View();
        }
        public void SendMail(long pid, string emailTo = "ahmedm.seada@gmail.com", string subject = "sub", string message = "")
        {


            PackagesInfo package = db.PackagesInfo.SingleOrDefault(x => x.PId == pid);

            var emailBody = $"<h4><span style=\"margin-left:2%%;\">Package {package.Description} Details: </span><p>ID : {package.PId}</p><p>Weight : {package.PWeight}</p><p>Price : {package.PPrice}</p><p>Sender ID : {package.SSsn}</p><p>Delevery Date :{package.Deleverydate.Value.ToShortDateString()}</p><p>Description : {package.Description}</p><span>To Track Your Package Visit : https://www.mds/ <br /> Regards<p>Regards <span style=\"color:#0474ac\">MDS Team &copy; {DateTime.Now.Year}</span></p></span></h4>";
            SendEmail(emailTo, "Your Order Recorded", emailBody);

        }


        public bool SendEmail(string toEmail, string subject, string emailBody)
        {
            try
            {

                string senderEmail = _config.GetValue(typeof(string), "senderEmail").ToString();
                string senderPassword = _config.GetValue(typeof(string), "senderPassword").ToString();
                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.Timeout = 100000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(senderEmail, senderPassword);
                MailMessage message = new MailMessage(senderEmail, toEmail, subject, emailBody);
                message.IsBodyHtml = true;
                message.BodyEncoding = UTF8Encoding.UTF8;
                client.Send(message);

                return true;
            }
            catch (Exception)
            {

                return false;
            }
        }

        private void SendMobileMessage(PackagesInfo p, string _mobile)
        {

            string usName = _config.GetValue(typeof(string), "un").ToString();
            string password = _config.GetValue(typeof(string), "passWord").ToString();
            string email = _config.GetValue(typeof(string), "email").ToString();
            string accpassword = _config.GetValue(typeof(string), "pass").ToString();
            string language = "1";
            string Sender = "MDS Team";
            string mobile = _mobile;
            string msg = $@"

Views/Shared/_Add.cshtml
@model Graduation_Core.Models.Employee

@{
    ViewData["Title"] = "Create";
}


<div class="alert alert-success text-center mx-auto">
    Add New Employee
</div>

@*Add Empolyee*@
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <table class="table mx-auto ">
        <tbody>
            <tr>
                <td>Name</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpName" class="form-control" />
                        <span asp-validation-for="EmpName" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Mobile</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpMobile" class="form-control" />
                        <span asp-validation-for="EmpMobile" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Email</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpEmail" class="form-control" />
                        <span asp-validation-for="EmpEmail" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Address</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpAddress" class="form-control" />
                        <span asp-validation-for="EmpAddress" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>SSN</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpSsn" class="form-control" />
                        <span asp-validation-for="EmpSsn" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>City</td>
                <td>
                    <div class="form-group">

                        <select asp-for="EmpCId" class="form-control" id="eCityAdd" asp-items="@ViewBag.cities"></select>
                        <span asp-validation-for="EmpCId" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Details</td>
                <td>
                    <div class="form-group">
                        <input asp-for="EmpAddressDetails" class="form-control" />
                        <span asp-validation-for="EmpAddressDetails" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr id="Loc">
                <td>Working Line</td>
                <td>
                    <div class="form-group">

                        <select asp-for="EmpLId" class="form-control" id="eLocationAdd" asp-items="ViewBag.locs"></select>
                        <span asp-validation-for="EmpLId" class="text-danger"></span>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <div>
        @*asas*@
        <div class="modal-footer">
            <a class="btn btn-secondary text-white" data-dismiss="modal" aria-label="Close"><i class="fas fa-chevron-circle-left "></i> Cancel</a>
            <button type="submit" class="btn btn-success"><i class="fas fa-save"></i>Create</button>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(document).ready(function () {
        $( "#Loc" ).hide();
        $('#eCityAdd').change(function () {
           var sel = document.getElementById('eCityAdd');
           var current = sel.value;
            $.ajax({

                url: '@Url.Action("getlocationsbyid","Employees")',
                data: { id: current },
                type: "GET",
                success: function (result) {
                    if (result.length > 1) {
                        $('#eLocationAdd').children().remove();
                        for (var i = 0; i < result.length; i++) {
                            var option = document.createElement('option');
                            option.value = result[i].value;
                            option.innerHTML = result[i].text;
                            $('#eLocationAdd').append(option);

                        }
                        $('#Loc').show();

                    }
                }
            });
        });
    });
</script>

Views/Shared/_Delete.cshtml
@model Graduation_Core.Models.Employee

@{
    ViewData["Title"] = "Delete";
}
<div class="alert alert-danger  text-center mx-auto" role="alert">
    Are you sure you want to delete @Model.EmpName
</div>
<table class="table mx-auto text-center">
    <tbody>
        <tr>
            <td>Name</td>
            <td>@Model.EmpName</td>
        </tr>
        <tr>
            <td>Mobile</td>

            <td>@Model.EmpMobile</td>
        </tr>
        <tr>
            <td>Email</td>

            <td>@Model.EmpEmail</td>
        </tr>
        <tr>
            <td>Address</td>

            <td>@Model.EmpAddress</td>
        </tr>
        <tr>
            <td>SSN</td>

            <td>@Model.EmpSsn</td>
        </tr>
        <tr>
            <td>Details</td>

            <td>@Model.EmpAddressDetails</td>
        </tr>
        <tr>
            <td>City</td>

            <td>@Model.EmpC.CName</td>
        </tr>
        <tr>

            <td>Location</td>
            <td>@Model.EmpL.LTo</td>
        </tr>
    </tbody>
</table>
<hr />

<div class="row mx-auto">
    <a  class="btn btn-success text-white mx-auto"  data-dismiss="modal" aria-label="Close" ><i class="fas fa-chevron-circle-left "></i> Cancel</a>
    <form asp-action="Delete" class="mx-auto">
        <input type="hidden" asp-for="EmpId" />
        @Html.HiddenFor(m => m.EmpId)
        <button type="submit" class="btn btn-danger "><i class="fas fa-trash-alt "></i> Delete </button>
    </form>

</div>

Views/Shared/_Edit.cshtml
@model Graduation_Core.Models.Employee

@{
    ViewData["Title"] = "Edit";
}


<div class="alert alert-warning text-center mx-auto">
    You Are Editing Employee @Model.EmpName Data
</div>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="EmpId" />
    <table class="table">
        <tbody>
            <tr>
                <td>Name</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpName" class="form-control" />
                        <span asp-validation-for="EmpName" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Mobile</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpMobile" class="form-control" />
                        <span asp-validation-for="EmpMobile" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Email</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpEmail" class="form-control" />
                        <span asp-validation-for="EmpEmail" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Address</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpAddress" class="form-control" />
                        <span asp-validation-for="EmpAddress" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>SSN</td>
                <td>
                    <div class="form-group">

                        <input asp-for="EmpSsn" class="form-control" />
                        <span asp-validation-for="EmpSsn" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>City</td>
                <td>
                    <div class="form-group">
                        <select asp-for="EmpCId" class="form-control" id="eCity" asp-items="@ViewBag.cities"></select>
                        <span asp-validation-for="EmpCId" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Details</td>
                <td>
                    <div class="form-group">
                        <input asp-for="EmpAddressDetails" class="form-control" />
                        <span asp-validation-for="EmpAddressDetails" class="text-danger"></span>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Working Line</td>
                <td>
                    <div class="form-group">

                        <select asp-for="EmpLId" class="form-control" id="eLocation" asp-items="ViewBag.locs"></select>
                        <span asp-validation-for="EmpLId" class="text-danger"></span>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <div>
        <div class="modal-footer" role="alert">
            <a asp-action="Index" class="btn btn-success" data-dismiss="modal" aria-label="Close"><i class="fas fa-chevron-circle-left "></i> Close</a>
            <button type="submit" class="btn btn-secondary text-white"><i class="fas fa-save"></i>Save</button>
        </div>

    </div>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(document).ready(function () {
       
        $('#eCity').change(function () {
           var sel = document.getElementById('eCity');
           var current = sel.value;
            $.ajax({

                url: '@Url.Action("getlocationsbyid","Employees")',
                data: { id: current },
                type: "GET",
                success: function (result) {
                    if (result.length > 1) {
                        $('#eLocation').children().remove();
                        for (var i = 0; i < result.length; i++) {
                            var option = document.createElement('option');
                            option.value = result[i].value;
                            option.innerHTML = result[i].text;
                            $('#eLocation').append(option);
                            $('#eLocation').show();
                            
                        }
                    }
                }
            });
        });
    });
</script>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Session;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

        <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-light bg-light justify-content-between bg-dark">
            <a class="navbar-brand text-white" href="~/home/index">MDS</a>
            @{
                var usrName = @HttpContextAccessor.HttpContext.Session.GetString("username");
            }
            @if (usrName != null)
            {
                <div class="form-inline">
                    <p class="text-white mr-sm-4  my-2 my-sm-2"> ID : @HttpContextAccessor.HttpContext.Session.GetString("uid")</p>

                    <div class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle text-white mr-sm-4  my-2 my-sm-2" data-toggle="dropdown" href="~/manage/index?id=@int.Parse(HttpContextAccessor.HttpContext.Session.GetString("uid").ToString())" role="button" aria-haspopup="true" aria-expanded="false">@usrName</a>
                        <div class="dropdown-menu ">
                            <a class="dropdown-item" href="~/manage/profile">Profile</a>
                            <a class="dropdown-item" href="~/manage/edit">Edit</a>
                            <a href="~/manage/logout" class="btn btn-outline-success my-2 my-sm-0 dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <form class="form-inline" asp-action="login" asp-controller="Manage" method="post">
                    <input type="text" name="UserName" class="form-control mr-sm-2" placeholder="Username" />
                    <input type="password" name="Password" class="form-control mr-sm-2" placeholder="Password" />
                    <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Login</button>
                    <a href="~/manage/register" class="btn btn-outline-success my-2 my-sm-0" style="margin-left:5px">Rigster</a>
                </form>
            }
        </nav>
    </header>

    <partial name="_CookieConsentPartial" />

    @RenderBody()

    <div class="accordion col-lg-4 col-sm-12 fixed-bottom " style="border:none" id="chatExample">
        <div class="card">
            <div class="card-header btn  text-white" style="background:#0474ac;border-radius:15px 15px 0px 0px;border:none;outline:none" id="headingChat" data-toggle="collapse" data-target="#openChat" aria-expanded="true" aria-controls="collapseOne">
                Open Chat
            </div>
            <div id="openChat" style="border:none" class="collapse show" aria-labelledby="headingChat" data-parent="#chatExample">
                <iframe src='https://webchat.botframework.com/embed/mdschat-bot?s=c5J_3R34ciA.HyadPzuK8yjCQCjs076hpjWKN14U1nGeprIq1YRh4pU' style='width: 100%; min-height: 350px;padding:0px;margin:0px;'></iframe>
            </div>
        </div>
    </div>


    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; @DateTime.Now.Year - MDS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#headingChat').click();
    });
    $(document).focus();
</script>

Views/Shared/_PackageDetails.cshtml
@model Graduation_Core.Models.PackagesInfo
<link href="~/css/site.css" rel="stylesheet" />
<table class="table">
    <thead>
        <tr>
            <th>Wieght</th>
            <th>Fragial</th>
            <th>Price</th>
            <th>Description</th>
            <th>Early Delivery</th>
            <th>Delivery Date</th>
            <th>Sender</th>
            <th>Reciever</th>
            <th>Line</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.PWeight</td>
            <td>@Model.PFaragial</td>
            <td>@Model.PPrice</td>
            <td>@Model.Description</td>
            <td>@Model.Earlydelivery</td>
            <td>@Model.Deleverydate</td>
            <td>@{var sender = new DMSContext().SenderInfo.FirstOrDefault(s => s.SSsn == Model.SSsn);} <a data-toggle="modal" data-target="#senderModal-@Model.PId" href="#">@sender.SName</a></td>
            <td>@{var reciver = new DMSContext().ReceiverInfo.FirstOrDefault(r => r.RSsn == Model.RSsn);} <a data-toggle="modal" data-target="#reciverModal-@Model.PId" href="#">@reciver.RName</a> </td>
            <td>
                @{
                    var loc = new DMSContext().Locations.FirstOrDefault(l => l.LId == Model.PLId);
                    var line = loc.LFrom + " <===> " + loc.LTo;

                }
                @line
            </td>
        </tr>
    </tbody>
</table>


<div class="modal fade" id="senderModal-@Model.PId" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <partial name="_SenderDetails" model="@sender"/>
            </div>

        </div>
    </div>
</div>
<div class="modal fade" id="reciverModal-@Model.PId" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <partial name="_ReciverView" model="@reciver" />
            </div>

        </div>
    </div>
</div>

Views/Shared/_ReciverView.cshtml
@model Graduation_Core.Models.ReceiverInfo

    <div class="alert alert-success mx-auto text-center">
        Reciver @Model.RName Info
    </div>
<table class="table table-striped">
    <tbody>
        <tr>
            <td>Name</td>
            <td>@Model.RName</td>
        </tr>
        <tr>
            <td>Mobile</td>
            <td>@Model.RMobile</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>@Model.REmail</td>
        </tr>
        <tr>
            <td>SSN</td>
            <td>@Model.RSsn</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>@Model.RAddress</td>
        </tr>
        <tr>
            <td>Details</td>
            <td>@Model.RAddressDetail</td>
        </tr>
        <tr>
            <td>City</td>
            <td>@{var rc = new DMSContext().City.FirstOrDefault(c => c.CId == Model.RCId).CName;} @rc</td>
        </tr>
        <tr>
            <td>Sender</td>
            <td>@{var sndr = new DMSContext().SenderInfo.FirstOrDefault(sn => sn.SId == Model.SId).SName;} @sndr</td>
        </tr>
    </tbody>
</table>
<div class="modal-footer">
    <a class="btn btn-secondary text-white" data-dismiss="modal" aria-label="Close"><i class="fas fa-chevron-circle-left "></i> Cancel</a>
</div>

Views/Shared/_SenderDetails.cshtml
@model Graduation_Core.Models.SenderInfo
<div class="alert alert-success mx-auto text-center">
    Sender @Model.SName Info
</div>
    <table class="table table-striped">
        <tbody>
            <tr>
                <td>Name</td>
                <td>@Model.SName</td>
            </tr>
            <tr>
                <td>Mobile</td>
                <td>@Model.SMobile</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>@Model.SEmail</td>
            </tr>
            <tr>
                <td>SSN</td>
                <td>@Model.SSsn</td>
            </tr>
            <tr>
                <td>Address</td>
                <td>@Model.SAddress</td>
            </tr>
            <tr>
                <td>Details</td>
                <td>@Model.SAddressDetail</td>
            </tr>
            <tr>
                <td>City</td>
                <td>@{var sc = new DMSContext().City.FirstOrDefault(c => c.CId == Model.SCId).CName;} @sc</td>
            </tr>
        </tbody>
    </table>

<div class="modal-footer">
    <a class="btn btn-secondary text-white" data-dismiss="modal" aria-label="Close"><i class="fas fa-chevron-circle-left "></i> Cancel</a>
</div>

Views/Shared/_Sent.cshtml
<h1 class="text-center text-success" > Email Sent Succeffuly </h1>

Views/Shared/_TrackPackage.cshtml
<div class="container" id="trackPanel">
    @using (Html.BeginForm("Track", "Package", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <input type="text" name="id" class="form-control" placeholder="Package ID" />
        </div>
        <input type="submit" value="Track" class="btn btn-success btn-block" />
    }
</div>